<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_islandora_derivative_alter().

      'dest_dsids' => array(
        'description' => 'Optional. A comma-separated list of datastream IDs to generate. If absent, all derivatives will be generated.' ,
      ),
      'skip_dsids' => array(
        'description' => 'Optional. A comma-separated list of datastream IDs to skip. If used with --dest_dsids, that option will be ignored.' ,
      ),


 */
function islandora_datastream_crud_islandora_derivative_alter(&$derivatives, AbstractObject $object) {
  if (drush_get_option('dest_dsids', FALSE)) {
    $dsid_list = drush_get_option('dest_dsids');
    $dsid_list = rtrim($dsid_list, ',');
    $dsids = explode(',', $dsid_list);
    foreach ($derivatives as $key => $derivative) {
      if (!in_array($derivative['destination_dsid'], $dsids)) {
        unset($derivatives[$key]);
      }
    }
  }
  if (drush_get_option('skip_dsids', FALSE)) {
    $dsid_list = drush_get_option('skip_dsids');
    $dsid_list = rtrim($dsid_list, ',');
    $dsids = explode(',', $dsid_list);
    foreach ($derivatives as $key => $derivative) {
      if (in_array($derivative['destination_dsid'], $dsids)) {
        unset($derivatives[$key]);
      }
    }
  }
}
